config/routes.rb
Rails.application.routes.draw do
  get 'main/welcome'

  resources :images

  resources :products do
    collection do
      post "import"
      get "images_upload"
      delete "remove_img"
    end
  end

  resources :categories do
    collection do
      post "savesort"
    end
  end

   root 'main#welcome'

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :products 
  
  scope :sorted, -> {order(:name)}
  default_scope { sorted }
  
  acts_as_nested_set
  
  validates :name, presence: true
  
  before_save :set_slug

  def descendents
    children.map do |child|
      [child] + child.descendents
    end.flatten.compact + [self]
  end

  protected

  def set_slug
    self.slug = self.name if self.slug.blank?
  end
  
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :product
  validates :img, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  validates :name, :price, presence: true
  before_save :set_slug_and_img
  
  belongs_to :category
  has_many :images
  
  

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = find_by_id(row["id"]) || new
      product.attributes = row.to_hash.slice(*row.to_hash.keys)
      product.save!
    end
  end



  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.csv' then Roo::Csv.new(file.path)
    when '.xls' then Roo::Excel.new(file.path)
    when '.xlsx' then Roo::Excelx.new(file.path)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end


  
  
  protected

  def set_slug_and_img
    self.slug = self.name if self.slug.blank?
#    self.img = self.img.original_filename unless self.img.blank?
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  http_basic_authenticate_with name: "123", password: "123" , except: :welcome
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]


  def index
    @categories = Category.order(:lft)
  end


  def new
    @category = Category.new
  end

  def edit
  end


  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  def savesort
    neworder = JSON.parse(params[:set])
    prev_item = nil
    neworder.each do |item|
      dbitem = Category.find(item['id'][2..-1])
      prev_item.nil? ? dbitem.move_to_root : dbitem.move_to_right_of(prev_item)
      sort_children(item, dbitem) unless item['children'].nil?
      prev_item = dbitem
    end
    Category.rebuild!
    @categories = Category.order(:lft)
    render 'index'
  end

  def sort_children(element,dbitem)
    prevchild = nil
    element['children'].each do |child|
      childitem = Category.find(child['id'][2..-1])
      prevchild.nil? ? childitem.move_to_child_of(dbitem) : childitem.move_to_right_of(prevchild)
      sort_children(child, childitem) unless child['children'].nil?
      prevchild = childitem
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :slug, :parent_id, :lft, :rgt)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def welcome
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]


  def index
    @products = Product.all.includes(:images)
  end


  def new
    @product = Product.new
#    @image = Image.new
  end

  def edit
#    @images = @product.images if @product.images.any?
#    @image = Image.new
  end

  def create
    upload_image(params[:product][:img]) unless params[:product][:img].blank?
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { 
          upload_add_images params[:add_img].values, @product  unless params[:add_img].blank?
          redirect_to products_url, notice: 'Товар сохранен' 
          }
      else
        format.html { render :new }
      end
    end
  end


  def update
    respond_to do |format|
      upload_image(params[:product][:img]) unless params[:product][:img].blank?
      if @product.update(product_params)
        format.html do
          upload_add_images params[:add_img].values, @product unless params[:add_img].blank?
          redirect_to products_url, notice: 'Товар сохранен'
        end
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Товар удален' }
    end
  end
  
  def import
    Product.import(params[:file])
    redirect_to products_url, notice: 'XLS загружен'
  rescue
    redirect_to products_url, notice: 'Ошибка при загрузке XLS'
  end

  def images_upload
    #@image_name = params[:file].original_filename
    #upload_image params[:file]
  end
  
  def remove_img
    @img = Image.find(params[:id])
    @img_id = @img.id
    @img.destroy
    respond_to do |format|
      format.js { render js: "$('.img_#{@img_id}').remove()"}
    end
  end
  
  private
  
    def upload_add_images images, product
      images.each do |img|
        upload_image img
        image = Image.new(img: img.original_filename)
        product.images << image
      end
    end


   def upload_image image
     File.open(Rails.root.join('public/img', image.original_filename), 'wb') do |file|
      file.write(image.read)
    end
   end
   
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
      @images = @product.images
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params[:product][:img] = params[:product][:img].original_filename unless params[:product][:img].blank?
      params.require(:product).permit(:name, :slug, :category_id, :descr, :price, :img)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_children.html.haml
%ul{:id => "c#{item.id}", :style => "display: none;"}
  - item.children.each do |category|
    %li{:id => "cc#{category.id}"}
      %div
        = category.name
        - unless category.leaf?
          %span.glyphicon.glyphicon-plus{:onclick => "$('#c#{category.id}').toggle()", :style => "cursor: pointer;"}
        %span.del{:title => "Удалить"}= link_to image_tag("remove.png"), category, method: :delete, data: { confirm: 'Точно?' } 
        %span.edit= link_to image_tag("edit.png"), edit_category_path(category)
        %span.new= link_to 'Добавить категорию', new_category_path(id: category.id), class: "btn btn-primary btn-xs" 
      = render 'children', :item => category unless category.leaf?

app/views/categories/_form.html.haml
.col-md-offset-2.col-md-8
  - if @category.errors.any?
    #error_explanation
      %h2 Ошибок: #{@category.errors.count}
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg  

  = form_for @category do |f|
    %table
      %tr
        %th= f.label :parent_id, "Родитель"
        %td= f.select :parent_id, nested_set_options(Category, @category) {|i| "#{'++++   ' * i.level} #{i.name}" }, |
                  { selected: @category.child? ? @category.parent_id : nil, include_blank: "Нет" } 
      %tr
        %th= f.label :name, "Наименование" 
        %td= f.text_field :name
      %tr
        %th= f.label :slug, "Слаг"
        %td= f.text_field :slug

    = f.submit "Сохранить" , class: "btn btn-primary" 
    = link_to 'Вернуться', categories_path, class: "btn btn-default" 

app/views/categories/edit.html.haml
.page-header
  %h2 Редактирование категории


 = render 'form'

app/views/categories/index.html.haml
.page-header
  %h2 Категории товаров

.col-md-offset-2.col-md-8
  .well.well-sm 
    = link_to "Сохранить порядок категорий", url_for(action: "index"), id: "serialize", class: "btn btn-primary" 
    = link_to 'Создать категорию', new_category_path, class: "btn btn-success"

  %ul#sortable
    - for category in Category.roots
      %li{:id => "cc#{category.id}", :class => "#{cycle("","even")}"}
        %div
          %span.btn.btn-success.btn-xs= category.name
          - unless category.leaf? 
            %span.glyphicon.glyphicon-plus{:onclick => "$('#c#{category.id}').toggle()", :style => "cursor: pointer;"}
          %span.del{:title => "Удалить"}= link_to image_tag("remove.png"), category, method: :delete, data: { confirm: 'Точно?' }
          %span.edit= link_to image_tag("edit.png"), edit_category_path(category)
          %span.new= link_to 'Добавить категорию', new_category_path(id: category.id), class: "btn btn-primary btn-xs" 
        = render 'children', :item => category unless category.leaf?



:coffeescript 
  nestsort()

app/views/categories/new.html.haml
.page-header
  %h2 Новая категория


= render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Тестовый магазин. 
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default{:role => "navigation"}
      .container-fluid
        .navbar-header
          %button.navbar-toggle{:type => "button", :data => {:toggle => "collapse", :target => "#bs-example-navbar-collapse-1"}}
            %span.sr-only Toggle navigation
            %span.icon-bar
          %a.navbar-brand{:href => "/"} Тest
        .collapse.navbar-collapse#bs-example-navbar-collapse-1
          %ul.nav.navbar-nav
            %li{:class => "#{'active' if controller == 'products'}"}
              = link_to 'Товары', products_path
            %li{:class => "#{'active' if controller == 'categories'}"}
              = link_to 'Категории', categories_path

  .container.content
    - if flash
      - flash.each do |name, msg|
        .alert.alert-info.alert-dismissable
          = msg
          %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;

    #popup.col-lg-offset-2.col-lg-8.col-md-offset-2.col-md-8.col-sm-offset-1.col-sm-10.well.well-sm
      #popup_head.col-md-12 
        %span 
        #popup_close.glyphicon.glyphicon-remove-circle
      #popup_content

    = yield

app/views/main/welcome.html.haml
.page-header
  %h2 Тестовое задание
.well
  %p Логин: 123
  %p Пароль: 123

app/views/products/_add_image.html.haml
.form-group.input-group
  = file_field_tag "add_img[#{rand(100000)}]"
  %span.input-group-addon
    %i.glyphicon.glyphicon-remove{:style => "cursor: pointer"} 

:coffeescript
  $(".glyphicon-remove").click ->
    $(this).parents("div").eq(0).remove()
    return

app/views/products/_form.html.haml
.col-md-offset-2.col-md-8

  = form_for @product, html: { multipart: true } do |f|
    - if @product.errors.any?
      #error_explanation
        %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
        %ul
          - @product.errors.full_messages.each do |msg|
            %li= msg

    .form-group.input-group
      %span.input-group-addon
        %i Категория:
      = f.collection_select( :category_id, Category.all, :id, :name, |
        { prompt: @product.category_id ? nil : "Выберите категорию", |
        selected: @product.category_id }, class: 'form-control' )

    .form-group.input-group
      %span.input-group-addon
        %i Наименование:
      = f.text_field :name, class: "form-control"

    .form-group.input-group
      %span.input-group-addon
        %i Слаг:
      = f.text_field :slug, class: "form-control"

    .form-group.input-group
      %span.input-group-addon
        %i Описание:
      = f.text_area :descr, class: "form-control"

    .form-group.input-group
      %span.input-group-addon
        %i Цена:
      = f.number_field :price, class: "form-control"

    .row
      .col-lg-6
        .well.well-sm
          .form-group.input-group
            %span.btn.btn-success.btn-file
              Основное изображение ...
              = f.file_field :img
          = image_tag "/img/#{@product.img}" unless @product.img.blank?
      .col-lg-6
        .well.well-sm
          .form-group.input-group
            %span.btn.btn-success.glyphicon.glyphicon-plus#add_img
              Дополнительные изображения
          - @images.each do |img|
            #del_img{:title => "Удалить", :style => "cursor: pointer", :class => "img_#{img.id}"}
              = link_to image_tag("/img/#{img.img}", style: "height: 100px;"), remove_img_products_path(id: img.id), style: "height: 100px;", remote: true, :method => :delete, :data => { :confirm => 'Точно удалить?' } unless img.img.blank?
   
   

          #images_upload

    = f.submit 'Сохранить', class: "btn btn-primary"
    = link_to 'Вернуться', products_path, class: "btn btn-default pull-right"


:coffeescript
  $("#add_img").click ->
    $.get '/products/images_upload'

app/views/products/edit.html.haml
.page-header
  %h2 Редактирование товара

= render 'form'

app/views/products/images_upload.js.haml
$("#images_upload").append("#{j render 'add_image'}")

app/views/products/index.html.haml
.page-header
  %h2 Товары
.well.well-sm
  = link_to 'Добавить товар', new_product_path, class: "btn btn-primary"

  = form_tag import_products_path, multipart: true, class: "pull-right" do
    .form-group.input-group
      %span.btn.btn-success.btn-file
        Загрузить из XLS
        = file_field_tag :file 
      = submit_tag "Выбрать", class: "btn btn-default"




%table#products
  %thead
    %tr
      %th Изображение
      %th К-во доп. изображений
      %th Наменование
      %th Слаг
      %th Категория
      %th Описание
      %th Цена
      %th
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td= image_tag "/img/#{product.img}", style: "width: 40px" unless product.img.blank?
        %td= product.images.size
        %td= product.name
        %td= product.slug
        %td= product.category.name if product.category
        %td= product.descr
        %td= product.price
        %td.edit= link_to image_tag("edit.png"), edit_product_path(product)
        %td.del= link_to image_tag("remove.png"), product, :method => :delete, :data => { :confirm => 'Точно?' }

app/views/products/new.html.haml
.page-header
  %h2 Новый товар

= render 'form'